name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout revision
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - name: Install NPM dependencies
        run: yarn install --frozen-lockfile

      - name: Disable Next.js telemetry
        run: yarn next telemetry disable

      - name: Lint
        run: yarn lint
